import { NextRequest, NextResponse } from 'next/server';
import { createClient, createAdminClient } from '@/lib/supabase/server';
import { z } from 'zod';
import { checkRateLimit, RATE_LIMITS, getClientIdentifier, createRateLimitHeaders } from '@/lib/rate-limit';

// Schema for team creation - now with defaultLeaveDays set by team creator
const createTeamSchema = z.object({
  name: z.string().min(2, 'Le nom doit contenir au moins 2 caractères').max(50),
  description: z.string().max(200).optional(),
  sector: z.enum(['public', 'private']).default('public'),
  defaultLeaveDays: z.number().min(0).max(60).default(25),
});

// POST /api/teams - Create a new team
export async function POST(request: NextRequest) {
  // Rate limiting
  const clientId = getClientIdentifier(request.headers);
  const rateLimitResult = checkRateLimit(`teams:${clientId}`, RATE_LIMITS.teams);

  if (!rateLimitResult.success) {
    return NextResponse.json(
      { error: 'Trop de requêtes. Réessayez plus tard.' },
      { status: 429, headers: createRateLimitHeaders(rateLimitResult) }
    );
  }

  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Non authentifié' },
        { status: 401 }
      );
    }

    // Use admin client for database operations (bypasses RLS)
    let adminClient;
    try {
      adminClient = createAdminClient();
    } catch {
      return NextResponse.json(
        { error: 'Configuration serveur manquante. Contactez l\'administrateur.' },
        { status: 500 }
      );
    }

    // Ensure user profile exists (create if not)
    const { data: existingProfile } = await adminClient
      .from('profiles')
      .select('id')
      .eq('id', user.id)
      .single();

    if (!existingProfile) {
      // Create profile if it doesn't exist (for users created before migration)
      const { error: profileError } = await adminClient
        .from('profiles')
        .insert({
          id: user.id,
          email: user.email,
          full_name: user.user_metadata?.full_name || '',
          first_name: user.user_metadata?.first_name || '',
          last_name: user.user_metadata?.last_name || '',
        });

      if (profileError) {
        console.error('Error creating profile:', profileError);
        return NextResponse.json(
          { error: 'Erreur lors de la création du profil utilisateur' },
          { status: 500 }
        );
      }
    }

    // Check if user already has a team
    const { data: existingMembership } = await adminClient
      .from('team_members')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (existingMembership) {
      return NextResponse.json(
        { error: 'Vous êtes déjà membre d\'une équipe' },
        { status: 409 }
      );
    }

    // Parse and validate request body
    const body = await request.json();
    const validationResult = createTeamSchema.safeParse(body);

    if (!validationResult.success) {
      return NextResponse.json(
        { error: validationResult.error.errors[0].message },
        { status: 400 }
      );
    }

    const { name, description, sector, defaultLeaveDays } = validationResult.data;

    // Create team with sector and default leave days (code is auto-generated by trigger)
    const { data: team, error: teamError } = await adminClient
      .from('teams')
      .insert({
        name,
        description,
        sector,
        default_leave_days: defaultLeaveDays,
        created_by: user.id,
      })
      .select()
      .single();

    if (teamError) {
      console.error('Error creating team:', teamError);
      // Check for specific errors
      if (teamError.code === '23505') {
        return NextResponse.json(
          { error: 'Une équipe avec ce code existe déjà. Veuillez réessayer.' },
          { status: 409 }
        );
      }
      if (teamError.code === '42501') {
        return NextResponse.json(
          { error: 'Permission refusée. Contactez l\'administrateur.' },
          { status: 403 }
        );
      }
      return NextResponse.json(
        { error: 'Erreur lors de la création de l\'équipe' },
        { status: 500 }
      );
    }

    // Validate that code was generated correctly (defensive programming)
    if (!team?.code || !/^[A-Z0-9]{8}$/.test(team.code)) {
      console.error('Invalid team code generated:', team?.code);
      // Rollback: delete the team
      await adminClient.from('teams').delete().eq('id', team.id);
      return NextResponse.json(
        { error: 'Erreur lors de la génération du code équipe. Veuillez réessayer.' },
        { status: 500 }
      );
    }

    // Add user as leader with team's default leave days
    const { data: membership, error: memberError } = await adminClient
      .from('team_members')
      .insert({
        user_id: user.id,
        team_id: team.id,
        role: 'leader',
        employee_type: 'employee',
        annual_leave_days: defaultLeaveDays,
        leave_balance: defaultLeaveDays,
        leave_balance_year: new Date().getFullYear(),
      })
      .select()
      .single();

    if (memberError) {
      // Rollback: delete the team
      const { error: deleteError } = await adminClient.from('teams').delete().eq('id', team.id);
      if (deleteError) {
        console.error('Failed to rollback team creation:', deleteError);
      }
      console.error('Error adding leader:', memberError);
      return NextResponse.json(
        { error: 'Erreur lors de l\'ajout du leader' },
        { status: 500 }
      );
    }

    // Update user's profile with current team
    const { error: profileUpdateError } = await adminClient
      .from('profiles')
      .update({ current_team_id: team.id })
      .eq('id', user.id);

    if (profileUpdateError) {
      // Rollback everything if profile update fails
      console.error('Error updating profile:', profileUpdateError);
      await adminClient.from('team_members').delete().eq('id', membership.id);
      await adminClient.from('teams').delete().eq('id', team.id);
      return NextResponse.json(
        { error: 'Erreur lors de la configuration du profil' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      team,
      membership,
      message: 'Équipe créée avec succès',
    }, { status: 201 });

  } catch (error) {
    console.error('Error in POST /api/teams:', error);
    return NextResponse.json(
      { error: 'Erreur serveur' },
      { status: 500 }
    );
  }
}

// GET /api/teams - Get current user's team
export async function GET() {
  try {
    const supabase = await createClient();

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Non authentifié' },
        { status: 401 }
      );
    }

    const { data: membership, error: memberError } = await supabase
      .from('team_members')
      .select(`
        *,
        team:teams(*)
      `)
      .eq('user_id', user.id)
      .single();

    if (memberError) {
      if (memberError.code === 'PGRST116') {
        return NextResponse.json({ team: null, membership: null });
      }
      throw memberError;
    }

    return NextResponse.json({
      team: membership.team,
      membership: {
        id: membership.id,
        role: membership.role,
        joined_at: membership.joined_at,
        employee_type: membership.employee_type,
        annual_leave_days: membership.annual_leave_days,
        leave_balance: membership.leave_balance,
      },
    });

  } catch (error) {
    console.error('Error in GET /api/teams:', error);
    return NextResponse.json(
      { error: 'Erreur serveur' },
      { status: 500 }
    );
  }
}
