import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { z } from 'zod';

// Schema for team creation
const createTeamSchema = z.object({
  name: z.string().min(2, 'Le nom doit contenir au moins 2 caractères').max(50),
  description: z.string().max(200).optional(),
});

// POST /api/teams - Create a new team
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Non authentifié' },
        { status: 401 }
      );
    }

    // Ensure user profile exists (create if not)
    const { data: existingProfile } = await supabase
      .from('profiles')
      .select('id')
      .eq('id', user.id)
      .single();

    if (!existingProfile) {
      // Create profile if it doesn't exist (for users created before migration)
      const { error: profileError } = await supabase
        .from('profiles')
        .insert({
          id: user.id,
          email: user.email,
          full_name: user.user_metadata?.full_name || '',
          first_name: user.user_metadata?.first_name || '',
          last_name: user.user_metadata?.last_name || '',
        });

      if (profileError) {
        console.error('Error creating profile:', profileError);
        return NextResponse.json(
          { error: 'Erreur lors de la création du profil utilisateur' },
          { status: 500 }
        );
      }
    }

    // Check if user already has a team
    const { data: existingMembership } = await supabase
      .from('team_members')
      .select('id')
      .eq('user_id', user.id)
      .single();

    if (existingMembership) {
      return NextResponse.json(
        { error: 'Vous êtes déjà membre d\'une équipe' },
        { status: 409 }
      );
    }

    // Parse and validate request body
    const body = await request.json();
    const validationResult = createTeamSchema.safeParse(body);

    if (!validationResult.success) {
      return NextResponse.json(
        { error: validationResult.error.errors[0].message },
        { status: 400 }
      );
    }

    const { name, description } = validationResult.data;

    // Create team (code is auto-generated by trigger)
    const { data: team, error: teamError } = await supabase
      .from('teams')
      .insert({
        name,
        description,
        created_by: user.id,
      })
      .select()
      .single();

    if (teamError) {
      console.error('Error creating team:', teamError);
      // Check for specific errors
      if (teamError.code === '23505') {
        return NextResponse.json(
          { error: 'Une équipe avec ce code existe déjà. Veuillez réessayer.' },
          { status: 409 }
        );
      }
      if (teamError.code === '42501') {
        return NextResponse.json(
          { error: 'Permission refusée. Contactez l\'administrateur.' },
          { status: 403 }
        );
      }
      return NextResponse.json(
        { error: `Erreur lors de la création de l'équipe: ${teamError.message}` },
        { status: 500 }
      );
    }

    // Add user as leader
    const { data: membership, error: memberError } = await supabase
      .from('team_members')
      .insert({
        user_id: user.id,
        team_id: team.id,
        role: 'leader',
      })
      .select()
      .single();

    if (memberError) {
      // Rollback: delete the team
      await supabase.from('teams').delete().eq('id', team.id);
      console.error('Error adding leader:', memberError);
      return NextResponse.json(
        { error: 'Erreur lors de l\'ajout du leader' },
        { status: 500 }
      );
    }

    // Update user's profile with current team
    await supabase
      .from('profiles')
      .update({ current_team_id: team.id })
      .eq('id', user.id);

    return NextResponse.json({
      team,
      membership,
      message: 'Équipe créée avec succès',
    }, { status: 201 });

  } catch (error) {
    console.error('Error in POST /api/teams:', error);
    return NextResponse.json(
      { error: 'Erreur serveur' },
      { status: 500 }
    );
  }
}

// GET /api/teams - Get current user's team
export async function GET() {
  try {
    const supabase = await createClient();

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Non authentifié' },
        { status: 401 }
      );
    }

    const { data: membership, error: memberError } = await supabase
      .from('team_members')
      .select(`
        *,
        team:teams(*)
      `)
      .eq('user_id', user.id)
      .single();

    if (memberError) {
      if (memberError.code === 'PGRST116') {
        return NextResponse.json({ team: null, membership: null });
      }
      throw memberError;
    }

    return NextResponse.json({
      team: membership.team,
      membership: {
        id: membership.id,
        role: membership.role,
        joined_at: membership.joined_at,
      },
    });

  } catch (error) {
    console.error('Error in GET /api/teams:', error);
    return NextResponse.json(
      { error: 'Erreur serveur' },
      { status: 500 }
    );
  }
}
